### PR TITLE
perf: optimize extraction of fill, stroke, responder, matrix & display

### PR DESCRIPTION
**Pull request by msand**
potentially breaking change
if any issues show up, then they'll be considered regressions
should be resolved in ways which cause less traffic from js to native

### CODE REVIEW

**Comment by msand** [comment]
Ideally we would get rid of empty font and proplist objects as well.

**Comment by msand** [comment]
@msageryd @wcandillon Would you mind testing this for performance changes and regressions?

**Comment by msand** [comment]
@SaeedZhiany @maxkomarychev @iqqmuT @kristerkari 🙏Could you help out as well? I think large svgs will notice the largest performance difference, probably most on low-end android. Especially if there are many G elements.

**Comment by msageryd** [comment]
@msand I tried 0fa4177 in my app and found no regressions. As of now I cannot tell anything about performance. I'll give it a go with a larger dataset in a couple of days. This is roughly what I tested:
- a couple of 100 elements on screen
- panning/zooming via setNativeProps (matrix)
- Moving and rotating elements
- Extensive use of caching with ``<Symbol>``

**Comment by msand** [comment]
Ah great, good to know. I'd expect that it requires really large svg documents to make it noticeable by eye, unless the device is really constrained in available cpu and memory. Might be that the difference is most noticeable in memory consumption. Should be at most a few percentage difference either way, unless one makes some kind of worst case example to exaggerate the difference, most of the work is still in rendering. But this also make e.g. browsing the element hierarchy much nicer in react native debugger, as there's much less noise now. 

I'd expect regressions to be mostly related to inheritance of fill and stroke, and possibly some geometry / transform related things, if any part is still relying on the transform props being extracted and sent using the extractProps helper.

**Pull request merged**
