### PR TITLE
Fixes #188 in the master repo by replacing the path in the import with the new path

### LINKED ISSUE #188: RN 0.38.0 causes issues with createReactNativeComponentClass (again)
RN 0.38.0 has a peer-dependancy of react@~15.4.0-rc.4 which removes `createReactNativeComponentClass` from `react/lib/createReactNativeComponentClass`

Not sure if this is the correct fix but I solved by updating references to `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass`

### PR DESCRIPTION
**Pull request by pablocarrillo**
This changes has been tested in our app and we didn't find any issue. The changes are a simple find and replace with the new path for the import and should be ok to be merged now. 
Thanks for all your effort in your awesome library.

### CODE REVIEW

**Comment by neiker** [comment]
Add >=15.4.0 as peer dependency

**Comment by scarlac** [comment]
Are there any outstanding issues with this patch which prevents it from being merged? Given the pace of RN it'd be nice to get this great library up and working with RN 0.38.

**Comment by manask88** [comment]
This is working well for me. What else will it take to have this merged? Please, let me know and I will see if there is something I can do to help get this merged. 
Thanks!

**Comment by magicismight** [comment]
Thanks for this PR.
I'll get this merged later.
Quite busy those days

**Pull request merged**
