### PR TITLE
Prefix iOS symbols with RNSVG

### PR DESCRIPTION
**Pull request by terribleben**
fixes https://github.com/react-native-community/react-native-svg/issues/603

Allows us to use a newer version of this lib in Expo.

### CODE REVIEW

**Comment by msand** [comment]
Looks great. Will test it and release new minor version.

**Comment by msand** [comment]
Published new version 6.2.0 Thanks for this!

**Comment by msand** [comment]
There was a minor issue with the paths https://github.com/react-native-community/react-native-svg/commit/13487029c07e3d0602e1bd61b554118919875875
Released a patched version 6.2.1

**Comment by terribleben** [comment]
Oh weird. Maybe due to the way I was testing (from inside the Example submodule)? Sorry about that

**Pull request merged**
