### PR TITLE
Prevents early rendering.

### PR DESCRIPTION
**Pull request by Orbyt**
Related to #921.

### CODE REVIEW

**Comment by Orbyt** [comment]
@msand Does anything further need to be done before this can be merged?

**Comment by msand** [comment]
Is the separate width and height parts needed? If so, you can probably replace the width * height == 0 in the early predicate

**Comment by Orbyt** [comment]
@msand Which part are you referring to? 

There was previously a simple if block:
```
if (width == 0 || height == 0) {
    return null;
}
```
this was combined with the if statement above it as they both return `null`.

**Comment by msand** [comment]
Yeah, i just noticed that the code that was changing those values got removed/doesn't exist anymore, and only the product, or comparing both width and height to zero separately, is needed. Doing both is redundant now that they're only set once.

**Comment by Orbyt** [comment]
@msand Are you suggesting the removal of `width == 0 || height == 0` or `width * height == 0 ` found in the declaration of the `early` boolean?

**Comment by msand** [comment]
@Orbyt there's another pr https://github.com/react-native-community/react-native-svg/pull/925 to check for negative values as well, so I would remove the `width * height == 0`, and make it check for `width < 1 || height < 1` or <= 0, instead.

**Pull request merged**
