### PR TITLE
Data URI support for href in react-native-svg Image tag

### PR DESCRIPTION
**Pull request by gpminsuk**
Have not tested for iPhone yet. Opening PR for discussions.

### CODE REVIEW

**Comment by gpminsuk** [comment]
Because Image in react-native-svg does not support asynchronous loading on iOS, this code change is to allow data URI as well as local asset (i.e., require()) in href. With this, RESTful API can be called separately and change href accordingly after getting data URI response.

**Comment by tonylinyy** [comment]
hi,@magicismight,it is useful function,may i ask when will be merged,thanks~~

**Comment by jjhesk** [comment]
when does it add into the repo????????

**Comment by magicismight** [comment]
Thanks for this PR. 👍

**Comment by tonylinyy** [comment]
nice job~~👍

**Pull request merged**
