### PR TITLE
Added support for ForeignObject

### LINKED ISSUE #447: <ForeignObject> support
Forgive me if this is covered, but I've searched the documentation and the issues and see no reference to this.

Is `<foreignObject>` supported or on the roadmap?

### PR DESCRIPTION
**Pull request by SaeedZhiany**
# Summary
This PR adds `ForeignObject` support to this library and resolve #447 

## Test Plan

It can be used like this:

```js
<View style={{flex: 1, justifyContent: 'center'}}>
  <Svg height="50%">
    <Defs>
      <LinearGradient
        id="Gradient"
        gradientUnits="userSpaceOnUse"
        x1="0"
        y1="0"
        x2="800"
        y2="0">
        <Stop offset="0" stopColor="white" stopOpacity="0.2" />
        <Stop offset="1" stopColor="white" stopOpacity="1" />
      </LinearGradient>
      <Mask
        id="Mask"
        maskUnits="userSpaceOnUse"
        x="0"
        y="0"
        width="800"
        height="300">
        <Rect x="0" y="0" width="800" height="300" fill="url(#Gradient)" />
      </Mask>
    </Defs>
    <G mask="url(#Mask)">
      <Circle cx={50} cy={70} r={65} />
      <ForeignObject x={50} y={50}>
        <View style={{width: 200, height: 400, flex: 1}}>
          <Image
            style={{width: 200, height: 200}}
            source={{
              uri: 'https://picsum.photos/200/200',
            }}
          />
        </View>
        <ForeignObject x={50} y={50}>
          <View style={{transform: []}}>
            <Text style={{color: 'blue'}}>Testing</Text>
            <Text style={{color: 'green'}}>Testing2</Text>
          </View>
        </ForeignObject>
      </ForeignObject>
    </G>
  </Svg>
</View>
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@msand 

currently, I'm getting this error
image

**Comment by SaeedZhiany** [comment]
@msand

currently, I'm getting this error
Screenshot_1578390972

**Comment by msand** [comment]
Did you run pod install ? And rebuild the app?

**Comment by SaeedZhiany** [comment]
I haven't tested it on mac yet, this is Android app. and yes I reinstall the app

**Comment by msand** [comment]
Do the files show up in android studio?

**Comment by SaeedZhiany** [comment]
yes

image

**Comment by SaeedZhiany** [comment]
Does `ForeignObject` need to override `saveDefinition` method?

**Comment by SaeedZhiany** [comment]
Ah, I think I found the problem, I forgot to add `ForeignObjectManager` instance in `createViewManagers` method

**Comment by SaeedZhiany** [comment]
Unfortunately, result is not what we want

image

**Comment by msand** [comment]
Ah, yeah, it probably needs some logic for clipping to the given bounds. And also inform yoga about the layout, or at least the width and height of the foreignElement, otherwise it won't be able to know how much it can flex / what percentages should refer to.

**Comment by SaeedZhiany** [comment]
But it extends G, so it should mimic `G`'s behavior. is it possible to convert `x` and `y` properties to `translate(x, y)`? because this library already can support foreignObject but using `G` syntax, we should try to build `<G translate(x, y)>` using `<ForeignObject x={} y={}>`, am I right?

**Comment by msand** [comment]
Well, actually, the G element doesn't have and y prop in the spec, any elements which have it should interpret it according to spec, although in this case it should behave exactly the same. The G element isn't specified to clip anything, the foreignobject is, and the spec is more the source of truth than what happens to inherit from what in the implementation.

**Comment by SaeedZhiany** [comment]
I'm not sure I could understand your mean or not. already we can nested any native view withing `G`, right?

```
<G translate(x, y)>
  <View>
    <Text>text1</Text>
    <Text>text2</Text>
    <Image/>
    ...
  </View>
</G>
```

and we want something like that:

```
<ForeignObject x={x} y={y}>
  <View>
    <Text>text1</Text>
    <Text>text2</Text>
    <Image/>
    ...
  </View>
</ForeignObject>
```

so I'm thinking of a way to convert `ForeignObject`'s `x` and `y` to `translate` property of `G`, isn't it possible? or I'm missing something else?

**Comment by msand** [comment]
For that it should be enough to replace 'withoutXY' with 'extract' in this one line: https://github.com/react-native-community/react-native-svg/pull/1242/files#diff-69a8312d4b83055c5e0312ee1cecbb09R28

**Comment by msand** [comment]
Also, foreignObjectProps should extend GProps https://github.com/react-native-community/react-native-svg/pull/1242/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R262

**Comment by msand** [comment]
Actually, better keep the withoutXY there, otherwise this will cause strange interaction when animating both x and y props and transform styles. The logic for handling the x and y props should be handled in the native side, overriding the rendering logic of G slightly. I can take a look at it later. Until then you can probably use the transform prop or style directly.

**Comment by SaeedZhiany** [comment]
So it seems the logic is more complicated than I think and unfortunately I haven't enough knowledge about that right now. Thanks for your notes. 👍

**Comment by msand** [comment]
Seems this renders the same across android ios and web now:

```jsx
import React, { Component } from "react";
import { Text, View, Image } from "react-native";
import {
  Svg,
  Defs,
  LinearGradient,
  Stop,
  Mask,
  Rect,
  G,
  Circle,
  ForeignObject
} from "react-native-svg";

export default class App extends Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: "center" }}>
        <Svg height="50%">
          <Defs>
            <LinearGradient
              id="Gradient"
              gradientUnits="userSpaceOnUse"
              x1="0"
              y1="0"
              x2="800"
              y2="0"
            >
              <Stop offset="0" stopColor="white" stopOpacity="0.2" />
              <Stop offset="1" stopColor="white" stopOpacity="1" />
            </LinearGradient>
            <Mask
              id="Mask"
              maskUnits="userSpaceOnUse"
              x="0"
              y="0"
              width="800"
              height="300"
            >
              <Rect
                x="0"
                y="0"
                width="800"
                height="300"
                fill="url(#Gradient)"
              />
            </Mask>
          </Defs>
          <G mask="url(#Mask)">
            <Circle cx={50} cy={70} r={65} />
            <ForeignObject x={50} y={0} width={100} height={100}>
              <View style={{ width: 200, height: 400, transform: [] }}>
                <Image
                    style={{ width: 200, height: 200 }}
                    source={{
                      uri: "https://picsum.photos/200/200"
                    }}
                />
              </View>
            </ForeignObject>
            <ForeignObject x={50} y={0} width={100} height={100}>
              <View style={{ width: 200, height: 400, transform: [] }}>
                <Text style={{ color: "blue" }}>Testing</Text>
                <Text style={{ color: "green" }}>Testing2</Text>
              </View>
            </ForeignObject>
          </G>
        </Svg>
      </View>
    );
  }
}

```

Screenshot 2020-01-11 at 21 34 10

**Pull request merged**
