### PR TITLE
separate npmignore entries into their related folders

### PR DESCRIPTION
**Pull request by SaeedZhiany**
# Summary

I took a look at my react-native-svg dependency in my project and I figure out even though some folders have been ignored in the root `.npmignore` file, they didn't actually ignore in the released version.
for example `build` folder in Android directory
image

So I tried to separate the npmignore entries into separated npmignore files in related folders to reduce the size of the release distributions.

## Test Plan

`npm pack --dry-run` to see what will be packaged.

**note**
I couldn't test it yet because of getting an error from `bob build` command. 
So I'm not sure I package everything needed. @msand please help me to complete this PR.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by msand** [comment]
Great, thanks for this!

**Comment by SaeedZhiany** [comment]
@msand 

This PR was also uncompleted and I asked you to test it before merging it.

> Test Plan
`npm pack --dry-run` to see what will be packaged.
**note**
I couldn't test it yet because of getting an error from bob build command.
So I'm not sure I package everything needed. @msand please help me to complete this PR.

the exact error stack trace is here
image

I have no idea what's going wrong and what is `flowgen` and `bob`. if you can guide me to remove this error I can do the rest.

However, most of the unnecessary files have been removed from the final package, but more additional is required in the android folder that you can see in the picture below. by removing them from release packages, their size will reduce about 1 MB again.

**The picture below belongs to  v9.13.5**

image

**Comment by msand** [comment]
Ah, I see. I only tested that it worked to install and use normally. Can you try running yarn or npm install inside the react-native-svg folder? then it should install the devdependencies, including flowgen and bob

**Comment by SaeedZhiany** [comment]
I have run `npm install`.
It installed some packages and it seems to install flowgen but have some problem with `bob`.

image

**Comment by msand** [comment]
Hmm, perhaps a bug in the windows support of https://github.com/react-native-community/bob

**Comment by msand** [comment]
Can you try moving the react-native-svg folder into a folder which doesn't have any spaces in the name, so instead of New folder, move it to e.g. desktop

**Comment by SaeedZhiany** [comment]
@msand 
It's a bug with bob package and I manage to skip it, you can read [this comment](https://github.com/react-native-community/bob/issues/2#issuecomment-564055504).

So I'll continue my work and submit another PR to ignore the remain file and folders from release npm packages.

**Pull request merged**
