### PR TITLE
Implement tailor made data structure and logic for text on a path, and various bugfixes.

### PR DESCRIPTION
**Pull request by msand**
Remove postinstall script and dependencies on PerformanceBezier & QuartzBookPack.
Needs some QA still, please help test.
Should resolve quite a few issues.

### CODE REVIEW

**Comment by kesha-antonov** [comment]
Waiting to get merged

**Comment by msand** [comment]
The transform parser had a particularly nasty bug, where it would ignore the exponents of any numbers.

**Comment by anonrig** [comment]
Can we get this merged please?

**Comment by louuysison** [comment]
+1 Need this PR

**Comment by msand** [comment]
I've just released 6.0.1-rc.2 which removes PerformanceBezier and QuartzBookPack. Can you please test it?
@kesha-antonov 
@anonrig 
@louuysison 
@ssssssssssss 
@adamski
@lukemiles

**Comment by simonbuchan** [comment]
"Wait, it doesn't support `transform`?" (googles) "40 minutes ago" That's Javascript!

**Comment by msand** [comment]
@simonbuchan Well, at this point it implements support for transform syntax fully and correctly, as far as I know. Or are you seeing any issues related to transforms at this point? And, how is this related to the language, rather than a specific library? Its not like obj-c or java or any lower level languages would have built in support for svg either. Conformant renderers seem quite hard to find even Qt, OpenFL and all the browsers: chrome, firefox, safari, ie, etc. still have issues after quite a few (thousand?) person-years of development.

**Comment by simonbuchan** [comment]
Blarg, I was a bit cryptic sorry. Just meant that less than an hour before I found out it wasn't implemented you released it 😊. Javascript only because I've had that sort of thing quite often... not so much with other ecosystems!

**Comment by msand** [comment]
Ah alright, I misunderstood 😄

**Pull request merged**
