### PR TITLE
5.4.0 conformance

### PR DESCRIPTION
**Pull request by msand**
Continuation of 5.3.0 conformance to 5.4.0

https://github.com/react-native-community/react-native-svg/pull/406
https://github.com/msand/react-native-svg/tree/5.4.0-conformance

### CODE REVIEW

**Comment by magicismight** [comment]
Merged into [6.0.0](https://github.com/react-native-community/react-native-svg/tree/6.0.0) branch .

**Comment by magicismight** [comment]
I have tested this on real device,
And it will crash every time with out of memory.
```
08-08 11:48:58.145 28549-32444/com.svgexample W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
08-08 11:48:58.145 28549-32444/com.svgexample E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
08-08 11:48:58.145 28549-32444/com.svgexample W/dalvikvm: threadid=16: thread exiting with uncaught exception (group=0x41675c50)
08-08 11:48:58.260 28549-28549/com.svgexample W/libc: pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
08-08 11:48:58.260 28549-28549/com.svgexample E/dalvikvm: pthread_create (stack size 16384 bytes) failed: Try again
08-08 11:48:58.260 28549-28549/com.svgexample W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41675c50)
```

**Comment by magicismight** [comment]
The out of memory crash never happened somehow.
I'm closing this, the continuation PR can be based on 6.0.0 branch.
The text and transform works perfectly. Great work!

**Comment by msand** [comment]
Wonderful, I thought it seemed a bit strange, couldn't come up with an explanation...
Great to hear! Thanks!

**Comment by awreese** [comment]
@magicismight @msand Great work both of you!  MM, it looks like you regularly bump versions, any idea as to when v6 will release?  I was really looking forward to msand's transform fixes (specifically for images).  Thanks.

**Comment by msand** [comment]
@awreese Thanks :) Now that ios is not crashing anymore because of my breaking changes, you can essentially use it. The ios text rendering isn't spec conformant yet, but I've started working on it. Not sure exactly how long it will take, as I have some obligations to deal with as well. But, essentially you can already start teting it just by: npm install --save react-native-svg@https://github.com/react-native-community/react-native-svg.git#6.0.0

**Comment by msand** [comment]
Oh of course, my ios fix is still only in my pull request / fork, so you need to use:
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#6.0.0

**Comment by msand** [comment]
@awreese @exKAZUu Check out https://github.com/react-native-community/react-native-svg/pull/430 
It has almost all the fixes from android ported to ios now. Most importantly ligatures and kerning need a bit more work, except for that, most everything seems to be working correctly. If you find any weakness/error, then please report it :)

**Pull request closed without merging**
