### PR TITLE
fix issue that not show transparent on android

### PR DESCRIPTION
**Pull request by xinyer**
set fill default value to transparent to fix the issue that can not show transparent background on Android.

### CODE REVIEW

**Comment by kevinjom** [comment]
Can we get this merged, I am having the same issue

**Comment by Amosel** [comment]
Why not both?

**Comment by msand** [comment]
Well, the spec https://www.w3.org/TR/SVG11/painting.html#FillProperties says that the default fill is black and the opacity is 1 so this seems like it'll probably break expectations. Do you have a some minimal test available which behaves differently from how e.g. browsers would render it?

**Comment by msand** [comment]
Can you try the latest version? I think I've fixed the real issue. WritableArray was reporting zero for non-empty arrays, when merging properties from ancestors more than one descendant deep in the tree. Rewrote it using ArrayList<String> instead.

**Comment by msand** [comment]
As no new information has arrived I'll assume this has been fixed. Closing.

**Pull request closed without merging**
