### PR TITLE
feat(android): Bidi

### PR DESCRIPTION
**Pull request by msand**
Should still add https://www.w3.org/TR/SVG2/text.html#DirectionProperty and make the default text direction depend on that.

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@msand 
Why this PR does not merge? it would be a great feature for RTL language developers

**Comment by msand** [comment]
Well, it's not really done, and I'm unable to know what is correct behavior as I cant read them. If you know any of these languages then please help fixing this.

**Comment by SaeedZhiany** [comment]
@msand 
Do you think this PR works for persian (farsi) language? I can read Persian, I readed your changes and it seems you added bidi and arabic language specific codes and I have no idea if it works for persian. I test it for persian as soon as possible and notify you

**Comment by SaeedZhiany** [comment]
@msand 
I can not find `TSpanShadowNode.java` file, it's seems has been removed or renamed, is this merged conflict related to the problem?

**Comment by SaeedZhiany** [comment]
however, I provide a simple sample that you can use it to verify your code in your free time. I put same "persian" string in both react native `Text` component and this library `Text` component. first one is the true rendering behavior and the second one is wrong.

```
import React, {Component} from 'react';
import {StyleSheet, Text as RNText, View} from 'react-native';
import Svg, {Text} from "react-native-svg";

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <RNText style={styles.RNText}>
          RN-Text: سلام
        </RNText>
        <Svg width="200" height="60">
          <Text
            fontSize="20"
            fontWeight="bold"
            textAnchor="middle"
            x="100"
            y="20"
          >
            SVG-Text: سلام
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  RNText: {
    fontSize: 20,
    fontWeight:"bold",
  }
});

```

Result screen shot:
screenshot_2018-11-15-16-49-09

**Comment by msand** [comment]
@SaeedZhiany Yeah, the file has changed, it's now a view instead of a shadow node: https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/TSpanView.java
Have you tried running using the commit in this branch?
yarn add react-native-svg@react-native-community/react-native-svg#bf230c4

**Comment by SaeedZhiany** [comment]
@msand, yes and this is the result:
It was able to display the letters in the correct order, but in Persian (and Arabic) letters have different ways of displaying and have some roles. For example, the letter "س" followed by the letter "ل" should be displayed as "سـ" and "ل" stick to it and same thing for "ل" and "ا"(this is equivalent for "a" in english, not capital "i"). I have no idea why this is so, I just guess that using a unicode font for presentation can solve problem.

photo_ - - _ - -

**Comment by SaeedZhiany** [comment]
> however, I provide a simple sample that you can use it to verify your code in your free time. I put same "persian" string in both react native `Text` component and this library `Text` component. first one is the true rendering behavior and the second one is wrong.
> 
> ```
> import React, {Component} from 'react';
> import {StyleSheet, Text as RNText, View} from 'react-native';
> import Svg, {Text} from "react-native-svg";
> 
> type Props = {};
> export default class App extends Component<Props> {
>   render() {
>     return (
>       <View style={styles.container}>
>         <RNText style={styles.RNText}>
>           RN-Text: سلام
>         </RNText>
>         <Svg width="200" height="60">
>           <Text
>             fontSize="20"
>             fontWeight="bold"
>             textAnchor="middle"
>             x="100"
>             y="20"
>           >
>             SVG-Text: سلام
>           </Text>
>         </Svg>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     justifyContent: 'center',
>     alignItems: 'center',
>     backgroundColor: '#F5FCFF',
>   },
>   RNText: {
>     fontSize: 20,
>     fontWeight:"bold",
>   }
> });
> ```
> Result screen shot:
> screenshot_2018-11-15-16-49-09

in this result, the "لا" has been rendered correctly, after using the commit it has been splitted that is not correct

**Comment by SaeedZhiany** [comment]
> however, I provide a simple sample that you can use it to verify your code in your free time. I put same "persian" string in both react native `Text` component and this library `Text` component. first one is the true rendering behavior and the second one is wrong.
> 
> ```
> import React, {Component} from 'react';
> import {StyleSheet, Text as RNText, View} from 'react-native';
> import Svg, {Text} from "react-native-svg";
> 
> type Props = {};
> export default class App extends Component<Props> {
>   render() {
>     return (
>       <View style={styles.container}>
>         <RNText style={styles.RNText}>
>           RN-Text: سلام
>         </RNText>
>         <Svg width="200" height="60">
>           <Text
>             fontSize="20"
>             fontWeight="bold"
>             textAnchor="middle"
>             x="100"
>             y="20"
>           >
>             SVG-Text: سلام
>           </Text>
>         </Svg>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     justifyContent: 'center',
>     alignItems: 'center',
>     backgroundColor: '#F5FCFF',
>   },
>   RNText: {
>     fontSize: 20,
>     fontWeight:"bold",
>   }
> });
> ```
> Result screen shot:
> 48555497-a6a17c80-e8f6-11e8-947e-32edfe1fd8c9

in this result, the "لا" has been rendered correctly, after using the commit it has been splitted that is not correct

**Comment by msand** [comment]
If someone is willing to work on this, it probably makes sense to look at how react-native handles this, and just doing the same.

**Comment by SaeedZhiany** [comment]
@msand and other peoples that want to help.

I figure out a new thing about the split rendering problem. it seems the used font features for painting is not correct. I don't familiar with this features. we must find and set correct settings for persian and arabic languages (this languages almost has same settings)

@msand would you please tell me where you pick the setting from? is there any documentation on this?

```
String required = "'rlig', 'liga', 'clig', 'calt', 'locl', 'ccmp', 'mark', 'mkmk',";
String defaultFeatures = required + "'kern', ";
String arabic = "'isol', 'fina', 'medi', 'init', 'rclt', 'mset', 'curs', "; <------
String defaultFeatures = required + arabic + "'kern', ";
```

**Comment by amerllica** [comment]
Dear @msand 

Please review, resolve conflicted file and merge this PR. We are extremely are wait for BiDi RTL support on Android. Thanks.

**Comment by msand** [comment]
Afaik, it's not working correctly and probably requires quite a bit of work still and I don't have any time to dedicate to it at the moment. Could you work on it? @amerllica

**Comment by BatDroid** [comment]
@boygirl i wish you could take a look at this cuz i saw that you have fixed sth related to rtl and persian/arabic language.

**Comment by amerllica** [comment]
Dear @BatDroid, If you have time for it, please fix this issue, @elmirafrhn told me the android side of issue is very simple but her time doesn't permit to pay attention to this issue.

**Comment by msand** [comment]
Have you seen this? https://github.com/react-native-community/react-native-svg/issues/439#issuecomment-524983074

**Comment by SaeedZhiany** [comment]
Great! is there any chance to get a new release any soon?

**Comment by SaeedZhiany** [comment]
@msand 
Thank you for your time on this Issue, I have tested the merged code in `develop` branch and here is the result, although the order of characters is correct they are completely disjoint from each other that is not correct.

Screenshot_1572419925

**Comment by msand** [comment]
https://yeslogic.com/blog/allsorts-rust-font-shaping-engine.html

**Comment by SaeedZhiany** [comment]
@msand 

Is this problem solved? I just read quickly the document and I saw that it says:

> Being a new project Allsorts does have some limitations: the crate is only lightly documented, and **_it doesn’t support shaping Arabic_** (Prince still uses its own Mercury implementation for this), Khmer, Tibetan, and Mongolian yet.

additionally, I test it again on v9.13.6. the result is the same as [this comment](https://github.com/react-native-community/react-native-svg/pull/724#issuecomment-547770431)

**Comment by msand** [comment]
Well, bidirectional text works better than before now at least. Arabic text shaping requires using the inlineSize attribute/prop for now, not supported with textpath or tspan with manual positioning of glyphs yet.

**Comment by SaeedZhiany** [comment]
can you show me an example? I couldn't see any difference with and without using `inlineSize` prop.

**Comment by msand** [comment]
Check e.g. here: https://github.com/react-native-community/react-native-svg/issues/439#issuecomment-524983074
https://github.com/react-native-community/react-native-svg/issues/1051#issuecomment-518292867

**Comment by SaeedZhiany** [comment]
I see know, I must use `TSpan` instead of `Text` component. Thanks

**Comment by SaeedZhiany** [comment]
Have you any plan to support it with `Text` component in the future? `TSpan` has some limitation like doesn't support `alignmentBaseline` prop that in my work is very necessary.

**Comment by msand** [comment]
Sure, it's not really spec compliant at this point, mostly a workaround to have at least some kind of support for line-breaking and arabic, indic, devanagari text shaping etc.

**Pull request merged**
