### PR TITLE
Remove references of RNSVGPercentageConverter file

### PR DESCRIPTION
**Pull request by jdnichollsc**
Clear references to fix issues building react-native-svg

# Summary
This PR fix this issue https://github.com/react-native-community/react-native-svg/issues/1123

### CODE REVIEW

**Comment by jdnichollsc** [comment]
@msand let me know what you think mate 👍

**Comment by msand** [comment]
Looks good, will publish a new version once I get to a computer in the morning

**Comment by sowmitranalla** [comment]
Would love to see this merged tomorrow!

Thanks!

**Comment by jdnichollsc** [comment]
Thanks Mikael for your support!

**Pull request merged**
