### PR TITLE
Optimize startup

### PR DESCRIPTION
**Pull request by msand**

### CODE REVIEW

**Comment by msand** [comment]
Ah ok. Well, I'm relatively confident the js code changes shouldn't break anything. But good get a bit more testing of it anyway.

**Comment by msand** [comment]
@msageryd I tried porting the caching logic to iOS now as well, available in the latest commit. Needs regression testing, and validation that it actually improves performance.

**Comment by msand** [comment]
Also, the memory retention needs to be analyzed.

**Comment by msand** [comment]
I think this might be ready for a release candidate to npm now. Unless someone finds a bug/regression.

**Comment by msageryd** [comment]
That sounds fantastic!
If you’re not in a hurry to release I’d be glad to help with some testing. I can do it on monday or maybe tuesday.



On 12 Jan 2019, at 22:47, Mikael Sand <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this might be ready for a release candidate to npm now. Unless someone finds a bug/regression.

**Comment by msageryd** [comment]
@msand Is the translation center fix related to #646 ?

**Comment by msageryd** [comment]
@msand when you say that memory retention needs to be analyzed, do you mean that this PR could fix  #893 ?

**Comment by msageryd** [comment]
#893 seems to be fixed by this PR.

**Comment by msageryd** [comment]
I still cannot get `<Use>`to work with rotation transforms as per #646 . I'm not certain that this PR was aimed to fix this or if I have made some error. @msand are you able to rotate **Use** elements with correct pivot point?

**Comment by msageryd** [comment]
Subjectively I see no performance boost. It's of course hard to see this by eye, but if the PR would , for example, have doubled the rendering performance I would have seen it. If there is a boost in the range of a couple of 10% I'm not sure I'd pick it up by eye.

**Comment by msand** [comment]
@msageryd Alright, great. As long as there's no noticeable regression of performance it should be fine. The improvements are probably mostly noticeable if a Svg element has several G elements with lots of content, but only one/a few of the groups get changed. In this case, it should be able to reuse the Path objects representing the unchanged groups. But splitting things into separate Svg roots, if they have different update frequencies, should still be faster. As it can reuse the entire bitmap/raster output in those cases and just do the composition using the normal view rendering.

Can you try the latest commit? It should fix handling of Use in iOS.

**Comment by msageryd** [comment]
I tried the latest commit as well (I saw the small iOS fix in this Android commit), but my positioning of `<Use>` element is still broke. It did change, though. My elements are now rendered in the lower right instead of the upper left corner (no transform applied to the **Use** element, but a parent Group (actually a grand-parent) has a scale transform.

**Comment by msand** [comment]
@msageryd Do you have any example where it renders different from normal svg use on the web? At least https://github.com/react-native-community/react-native-svg/issues/646#issuecomment-381366800 seems to render the same in the browser, ios and android for me now.

**Comment by msand** [comment]
screen shot 2019-01-14 at 16 21 47


```jsx
export default class App extends Component {
    render() {
        return (
            <Svg height="200" width="200" viewBox="0 0 100 100">
                <Symbol id="symbol" viewBox="0 0 100 100" width="10" height="10">
                    <Rect x="0" y="0" width="100" height="100" fill="blue" />
                    <Circle
                        cx="50"
                        cy="50"
                        r="40"
                        strokeWidth="8"
                        stroke="red"
                        fill="red"
                    />
                </Symbol>

                <Rect
                    x="0"
                    y="0"
                    width="100"
                    height="100"
                    stroke="blue"
                    fill="none"
                />
                <Use
                    href="#symbol"
                    x="0"
                    y="0"
                    width="20"
                    height="20"
                    transform="rotate(45, 10, 10)"
                />
                <Use
                    href="#symbol"
                    x="40"
                    y="40"
                    width="20"
                    height="20"
                    transform="rotate(-45, 10, 10)"
                />
                <Use
                    href="#symbol"
                    x="0"
                    y="80"
                    width="20"
                    height="20"
                    transform="rotate(-45, 10, 90)"
                />
            </Svg>
        );
    }
}
```

**Comment by msageryd** [comment]
I did restart the packager. Should I have deleted the ios/build folder as well?

**Comment by msand** [comment]
@msageryd Perhaps something like this might help:
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-*
react-native run-ios --reset-cache

**Comment by msageryd** [comment]
Good catch Mikael. I did a "Clean build folder" and a build from within XCode. It now works as before. But the pivot point still seems to be at the 0,0 of the root Svg and not 0,0 of the parent Group. Which should it be?

Here is 45 degree rotation:

image

**Comment by msageryd** [comment]
BTW. is the watchman and folder removals something that needs to be done everytime a native package is updated?

**Comment by msageryd** [comment]
My bad!
I thought I had the circle in a group which was positioned further out in the coordinate system. It turned out that X and Y of the parent group is in the upper left corner of the drawing.

Everything works perfectly when I add originX and originY to the transform.

I'd say **ship it** :)

@msand Thank you soo much for your outstanding work with RNSVG!

**Comment by msand** [comment]
These are actually for clearing the javascript cache, seems your native code had updated correctly, but used the old javascript for the react-native-svg module.
The origin of the Use element should be that of the containing element.
Thus e.g. in this content:

```html
    <svg height="200" width="200" viewBox="0 0 100 100">
      <symbol id="symbol" viewBox="0 0 100 100" width="10" height="10">
        <rect x="0" y="0" width="100" height="100" fill="blue" />
      </symbol>

      <g transform="translate(20, 20)">
        <rect x="0" y="0" width="100" height="100" stroke="blue" fill="none" strokeWidth="1" />
        <use href="#symbol" x="0" y="0" width="20" height="20" transform="rotate(45, 10, 10)" />
        <use href="#symbol" x="40" y="40" width="20" height="20" transform="rotate(-45, 10, 10)" />
        <use href="#symbol" x="0" y="80" width="20" height="20" transform="rotate(-45, 10, 90)" />
      </g>
    </svg>
```

you need to set the origin of the rotation using the optional x and y parameters of the rotate transform.
So, the non translated use element (all of which have width and height of 20 units), needs the origin at 10,10 to rotate about the center of it. And the use elements which have non-zero x or y attributes, need a different rotate definition to account for the translation.

**Comment by msand** [comment]
That syntax is probably more efficient (but non-standard / not part of the svg spec), as it is already in object form, while the string needs to be parsed using the transform parser. Otherwise they should be equivalent with regards to input/output. 
The only remaining question now is if this should be a major, minor or patch version. There is certainly potential for breaking changes, so I guess it should be a major one, although the affected users might be relatively few. Just hope it doesn't scare people away from updating.

**Comment by msand** [comment]
Oh, and btw, the bounds, center and frame calculation should fix the display of bounding boxes when using the inspector / standalone React Native Debugger, and it should improve pan responder and touch handling in several cases.

**Comment by msageryd** [comment]
Apart from the rare possibility of a bug in this PR, the only breaking change would be if someone already has solved the `<Use>` problem with some kind of workaround. 

Such a workaround would have been quite complicated and the person doing it would probably have search the Issues section before tampering with the workaround.

To me this is not a major patch. Expo is relying on RNSVG quite a bit, I think. Maybe @ide have any thought on major vs minor patch.

**Comment by msand** [comment]
True. Actually I already released v9.0.0
Although the potential for breaking change is relatively minor, it still changes the semantics/effects of the Use element x, y, and transform attributes. It's mostly in consideration of any user(s) who might have thought it was behaving correctly and found values which work for them using trial and error rather than using the standard / specified behavior of svg.

**Comment by msand** [comment]
Hmm, haven't seen that with font sizes. Could you make a repro?

**Comment by msageryd** [comment]
I really don't have time right now. I'll get back to you with a repro.
Here is a simple example of my workaround:

```
const VIRTUAL_TEXT_SCALE = 1000;

return (
  <Text
    transform={{scale: 1 / VIRTUAL_TEXT_SCALE}}
    fontSize={fontSize * VIRTUAL_TEXT_SCALE}
  >
    TEST
  </Text>
);
```

**Pull request merged**
