### PR TITLE
add missing imports in web root file

### PR DESCRIPTION
**Pull request by billouboq**
Hi, when working on web version of our app we just noticed some exports where missing in the web version.

This PR just add the missing ones.

### CODE REVIEW

**Comment by msand** [comment]
I would recommend using an img tag and set the svg content as a base64 encoded string, I'd expect the built-in parsers and css engines in browsers to be more efficient than this implementation.

**Comment by msand** [comment]
Alternatively, if you have a url, just use that with an img tag. Would you mind defining new components which do that, on the web, rather than process everything in js?

**Comment by billouboq** [comment]
Yeah of course, will do that ! thanks for your reply

**Comment by msand** [comment]
Actually don't need base64: https://css-tricks.com/probably-dont-base64-svg/

**Comment by billouboq** [comment]
Ok closing this, thanks

**Pull request closed without merging**
