### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by SaeedZhiany**
Upgrade android gradle plugin to latest version

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@msand 

I resolved merge conflicts, would you please check out this pull request?

**Comment by msand** [comment]
The use of safeExtGet in dependencies broke the build, reverted the change.

**Comment by SaeedZhiany** [comment]
@msand but Travis CI build has been passed, Are you sure it's because of this change?

**Comment by msand** [comment]
The ci only lints javascript, proper e2e tests are missing. Yeah, I'm sure, you can try for yourself.

**Pull request merged**
