### PR TITLE
Add Basic support to transform props, including translate, rotate, sc…

### PR DESCRIPTION
**Pull request by ssssssssssss**
…ale, skewX, skewY and matrix. Keep in mind that the current implementation doesn't support  3-arguments rotate(a, x, y) transform yet.

### CODE REVIEW

**Comment by vitorebatista** [comment]
Great 👍 
Please merge asap!

**Comment by adrianboimvaser** [comment]
I need this. Is it getting reviewed?

**Comment by icarv** [comment]
Sounds great, would scaleX, scaleY fit here too, might solve request/issue #354

**Comment by vitorebatista** [comment]
When will it merge?

**Comment by fendorio** [comment]
+1 This would be helpful to me also

**Comment by adrianboimvaser** [comment]
Is there anything we can do to help this get merged?

**Comment by magicismight** [comment]
It's already merge in [6.0.0] (https://github.com/react-native-community/react-native-svg/tree/6.0.0)

**Comment by henrikra** [comment]
@magicismight Why there hasn't been a new release?

**Comment by ssssssssssss** [comment]
@henrikra 6.0.0 contains some heavy undertakings and the iOS port is not merged yet. Please be patient. :)

**Pull request closed without merging**
