### PR TITLE
Fixes Android Release images not rendering (Issue #129)

### PR DESCRIPTION
**Pull request by jerzxu**
## Fixes Android Release images not rendering (Issue #129)

Issue caused by 2 things:

- Image resources were not properly getting the path due to missing scheme (if required via require('./images/img.png'))
- markUpdated() was not causing a re-render thus image was not updating if it was a resource id after fetching. This is been changed to directly call bitmapTryRender, however, this may not be the best approach to this issue.

Minor note: After making this change, RenderableShadowNode would get a null for images. I put a null check for the alpha parameter to suppress this.

### CODE REVIEW

**Comment by jerzxu** [comment]
I see a PR is open for my color work around (https://github.com/react-native-community/react-native-svg/pull/512). I will update this once that has been merged.

**Comment by dustinsavery** [comment]
@jerzxu #512 has been merged.

**Comment by dustinsavery** [comment]
@jerzxu #512 has been merged

**Comment by jerzxu** [comment]
@dustinsavery I've updated the PR reverting the color workaround

**Comment by dustinsavery** [comment]
Not super familiar with android, going to leave it open for comments for 48 hours and then merge.  @brentvatne, would appreciate another set of eyes here.

**Comment by nishiltamboli** [comment]
Wow that worked! :+1:  Good job @jerzxu . The images now show up. I can confirm local asset images are now visible with this PR.

**Pull request merged**
