### PR TITLE
Css

### PR DESCRIPTION
**Pull request by msand**
# Summary

Implement support for style elements when parsing svg xml content, or fetching from uri.

## Test Plan

```jsx
import React from 'react';
import {TouchableOpacity} from 'react-native';
import {parse} from 'react-native-svg';
import {inlineStyles, SvgCss} from 'react-native-svg/src/css';

const svgWithCssExample = `<svg xmlns="http://www.w3.org/2000/svg"
     width="100%" height="100%" viewBox="0 0 1000 500">
  <defs>
    <style type="text/css"><![CDATA[
      rect {
        fill: green;
        stroke: blue;
        stroke-width: 3
      }
    ]]></style>
  </defs>
  <rect x="200" y="100" width="600" height="300"/>
</svg>
`;

const App = () => {
  return (
    <TouchableOpacity
      style={{flex: 1, backgroundColor: 'blue'}}
      onPress={() => {
        const parsed = parse(svgWithCssExample, x => {
          let styled = inlineStyles(x);
          console.log({...styled});
          return styled;
        });
        console.log(parsed);
      }}>
      <SvgCss xml={svgWithCssExample} />
    </TouchableOpacity>
  );
};

export default App;

```

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by msand** [comment]
I'm thinking maybe this should be a separate module/package, then again, it might need changes in sync with the rest of the code from here. Wouldn't want to introduce runtime dependencies into this package. But perhaps it's better to have it for now, until tailor made implementations for this specific use-case can be made.

**Comment by msand** [comment]
Simpler example:

```jsx
import React from 'react';
import {SvgCss} from 'react-native-svg/src/css';

const xml = `
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="100%"
  height="100%"
  viewBox="0 0 1000 500"
>
  <defs>
    <style type="text/css">
      rect {
        fill: lightgreen;
        stroke: blue;
        stroke-width: 5;
      }
    </style>
  </defs>
  <rect x="200" y="100" width="600" height="300" />
</svg>
`;

const App = () => <SvgCss xml={xml} />;

export default App;

```

**Comment by msand** [comment]
@iqqmuT I've simplified CSSStyleDeclaration now, can you test it?

**Comment by iqqmuT** [comment]
Tested ee4b0d5 and CSS support seems to work very well! I tested with different CSS selectors:

```javascript
const App: () => React$Node = () => {
  const xml = `<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
     width="10cm" height="5cm" viewBox="0 0 1000 500">
  <defs>
    <style type="text/css">
      rect {
        fill: red;
      }
      g .cl-1, g rect {
	stroke: blue;
        stroke-width: 16
      }
      .cl-2.yellow {
        fill: yellow;
      }
    </style>
  </defs>
  <g>
    <rect class="cl-1" x="100" y="0" width="600" height="200" />
  </g>
  <g>
    <rect class="cl-2 yellow" x="100" y="350" width="600" height="200" />
  </g>
</svg>`;
  return (
    <SvgCss xml={xml} width="200" height="200" />
  );
};
```

Result:
Screenshot from 2019-10-20 20-53-50

**Comment by iqqmuT** [comment]
@msand If you want, I can write a test case with Jest?

**Comment by msand** [comment]
Ah, excellent, that sounds great!

**Comment by msand** [comment]
@iqqmuT Seems like making css-tree and css-select peerDependencies should keep the module dependency free for the users who do not use the css functionality, and the web bundle seems to have stayed the same: https://bundlephobia.com/result?p=react-native-svg@9.13.0

**Comment by msand** [comment]
Seems my plan to keep the module dependency free failed, metro tries to resolve the module even if the new css components aren't used. Made them proper dependencies instead of peers now.

**Comment by iqqmuT** [comment]
There you go: #1167 
Just tell if you wish it to be more verbose.

**Comment by msand** [comment]
This is good, thank you!

**Pull request merged**
