### PR TITLE
Fix createReactNativeComponentClass import statements

### PR DESCRIPTION
**Pull request by developer239**

### CODE REVIEW

**Comment by crazypixel** [comment]
when do you plan to merge it ?

**Comment by itchingpixels** [comment]
hey!

this is unfortunately blocking us using this library. it'd be great to merge it in!

**Comment by developer239** [comment]
Not sure if I fixed all of the problems though.

**Comment by Benornm** [comment]
why the **react-native-community** not raising the glove and fix this issue ?

**Comment by magicismight** [comment]
I'm not sure this would fix the problem for good.

`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js';` should works the same as `+import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass`

Could you update your `package.json`'s dependencies and `npm install`?
```
"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.4",
		"react-native-svg": "5.3.2"
	},
```

**Comment by magicismight** [comment]
```
$ npm ls react-native-svg
test@0.0.1
└── react-native-svg@5.3.2 

$ npm ls react-native
test@0.0.1
└── react-native@0.46.4 

$ npm ls react
test@0.0.1
└── react@16.0.0-alpha.12 
```

This works fine for me.

**Comment by itchingpixels** [comment]
Hi! What's the current status of this PR?

**Comment by markentingh** [comment]
please merge this so we can start using SVGs in our projects

**Comment by magicismight** [comment]
I'm not sure why `import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js';` would work differently with `import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass';`

But this would fix this problem for good.
```
import { __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED } from 'react-native';
const createReactNativeComponentClass = __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.createReactNativeComponentClass;
```

I'll release a version which contains this fix.

**Comment by luco** [comment]
I had to put `import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass.js';`

**Comment by magicismight** [comment]
Thanks for this PR.
Have this landed on 5.3.3.
But I didn't feature out why this works.

**Pull request merged**
