### PR TITLE
added Marker component to definition file

### LINKED ISSUE #1208: Marker types does not added to Path Props
# Bug
I'm getting typing error when using Marker props (like `markerMid`, `markerEnd`, ...) in `Path` component.

also IDEA is importing `Marker` component from `'react-native-svg/lib/typescript'` directory, is it correct? Why it is not import from `react-native-svg` just like the other components?

## Environment info

"react": "16.8.3",
"react-native": "0.59.10",

React native info output:

```bash
TS2322: Type '{ key: string; d: string; stroke: string; fill: string; strokeWidth: number; markerMid: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<PathProps, any, any>> & Readonly<PathProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'markerMid' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<PathProps, any, any>> & Readonly<PathProps> & Readonly<{ children?: ReactNode; }>'.
```

Library version: 9.13.3

## Reproducible sample code

### PR DESCRIPTION
**Pull request by SaeedZhiany**
# Summary
This PR adding missing Marker related type definition. fixes #1208 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@msand 
Please review this and tell me where is the Marker props you supported to add them to Path, line, Polyline, and Polygon classes.

**Comment by msand** [comment]
Great, thanks for this! The marker props apply to all shapes: https://www.w3.org/TR/SVG/shapes.html#TermShapeElement
https://www.w3.org/TR/SVG/painting.html#MarkerProperty
The
https://github.com/react-native-community/react-native-svg/blob/8c1a1737b052000569662d6f2539ffe3c47564ba/src/lib/extract/extractProps.ts#L66-L69
https://github.com/react-native-community/react-native-svg/blob/8c1a1737b052000569662d6f2539ffe3c47564ba/src/lib/extract/extractProps.ts#L102-L110
Which is used in: Circle, ClipPath, Ellipse, G, Image, Line, Mask, Path, Rect, Text, TextPath, TSpan and Use elements, so they'll be processed in more places than they should at the moment, but that's essentially bugs / unspecified behaviour. They should only apply to: ‘circle’, ‘ellipse’, ‘line’, ‘path’, ‘polygon’, ‘polyline’ and ‘rect’. And g elements, as the property should be inherited.

**Comment by SaeedZhiany** [comment]
@msand 
I'm just a little bit confused, are you want to refactor `extractProps` function to only return the props for the shapes you mentioned?

My concern on this PR is fixing the building crash in using of Marker component and the typescript error TS2322 when passing marker(Start/Mid/End) props to a shape component like Path.

**Comment by msand** [comment]
No need to refactor at this point, they shouldn't hurt afaik, can make another pr/issue if anything shows up. Thanks for this!

**Comment by SaeedZhiany** [comment]
@msand 
Actually, my work was not completed yet. this change only fixes build the crash. the TS2322 still remains. (however, I'm glad at least I can build my project in my CI server).

My question was about the Marker props that already supported in code and must be added to props of components like Path and the other shapes you mentioned before to fix TS2322 error message.

The props I could find are `markerStart`, `markerMid`, and `markerEnd` that their types should be a string.

**Comment by SaeedZhiany** [comment]
@msand 
Actually, my work was not completed yet. this change only fixes the build crash. the TS2322 still remains. (however, I'm glad at least I can build my project in my CI server).

My question was about the Marker props that already supported in code and must be added to props of components like Path and the other shapes you mentioned before to fix TS2322 error message.

The props I could find are `markerStart`, `markerMid`, and `markerEnd` that their types should be a string.

**Comment by SaeedZhiany** [comment]
@msand 
Actually, my work was not completed yet. this change only fixes the build crash. the TS2322 still remains. (however, I'm glad at least I can build my project in my CI server).

My question was about the Marker props that already supported in code and must be added to props of components like Path and the other shapes you mentioned before to fix TS2322 error message.

The props I could find are `markerStart`, `markerMid`, and `markerEnd` that their types should be a string.

**Important Note**
I just upgrade my dependency version to `9.13.5` but I'm getting error message below: (the same happens for `9.13.4`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-svg@9.13.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by SaeedZhiany** [comment]
@msand 
Actually, my work was not completed yet. this change only fixes the build crash. the TS2322 still remains. (however, I'm glad at least I can build my project in my CI server).

My question was about the Marker props that already supported in code and must be added to props of components like Path and the other shapes you mentioned before to fix TS2322 error message.

The props I could find are `markerStart`, `markerMid`, and `markerEnd` that their types should be a string.

**Important Note**
I just upgraded my dependency version to `9.13.5` but I'm getting error message below: (the same happens for `9.13.4`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-svg@9.13.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by msand** [comment]
Oh, my mistake, was rushing thru the PRs as I barely have any time to dedicate to this project atm.
There's also the marker prop in addition to the start, mid and end, it's used as a default, and the three others take precedence over it. Could make a new prop like CommonMaskProps but called CommonMarkerProps instead and add it to CommonPathProps here: https://github.com/SaeedZhiany/react-native-svg/blob/cf150875a0554d32d89e0a486e859af322960715/src/index.d.ts#L209-L222

**Comment by SaeedZhiany** [comment]
@msand 
Thanks,
are you mean is this enough users using a marker with Path (and other shapes)?

```
export interface CommonMarkerProps {
  markerStart?: string;
  markerMid?: string;
  markerEnd?: string;
}
```

I'll make another draft PR with your suggestion and I'll inform you.

**Comment by msand** [comment]
yeah, or with the addition of the default marker prop:

```ts
export interface CommonMarkerProps {
  marker?: string;
  markerStart?: string;
  markerMid?: string;
  markerEnd?: string;
}

export interface CommonPathProps
  extends FillProps,
    StrokeProps,
    ClipProps,
    TransformProps,
    VectorEffectProps,
    ResponderProps,
    TouchableProps,
    DefinitionProps,
    CommonMarkerProps,
    CommonMaskProps {}
```

**Comment by SaeedZhiany** [comment]
I'll send you a PR in a few seconds.

**Pull request merged**
