### PR TITLE
Implement basic support for unicode emoji

### PR DESCRIPTION
**Pull request by msand**

### CODE REVIEW

**Comment by boygirl** [comment]
@msand testing this branch in `victory-native` I see:

for 
```
<Text x={x} y={y} fontSize={30}>
  {String.fromCodePoint(0x1F63B)}
</Text>
```

screen shot 2018-08-01 at 12 51 18 pm

**Comment by boygirl** [comment]
@msand It looks like it's working on Android but not iOS. More information in this issue: https://github.com/FormidableLabs/victory-native/issues/331

**Comment by boygirl** [comment]
@msand it works in iOS for me now, too! 😻

**Comment by omorhefere** [comment]
Hi, has the pull request been merged?

**Pull request merged**
